name: "psme.info"
description: ""

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true

safe:        false
watch:       false    # deprecated
server:      false    # deprecated
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false